header_background_color:
  type: string
  default: ""
  description: 
    en: "Header background color in hexadecimal, css color name or Discourse color variable. Leave blank to use current default."
  
