header_color:
  type: string
  default: "255, 255, 255"
  description: "RGB color code for glass header, for example: 47, 79, 79."
transparency:
  type: float
  min: 0
  max: 1.0
  default: 1.0
  description: "Transparency percent as a decimal of 1, for example: 0.8 = 80%, 0.35 = 35%."
header_icons_color:
  type: string
  default: ""
  description: "RGB color code for header icons, for example: 47, 79, 79."
