header_color:
  type: string
  default: ""
  description: 
    en: "Header background color in hexadecimal, css color name or Discourse color variable. Leave blank to use current default."
  
transparency:
  type: integer
  default: 0
  description: 
    en: "Transparency in percentage decimal - ie: 0.5 = 50%, 0.35 = 35%."
